site_name: DEFIANT-FG
site_url: https://karlhunter.co.uk/defiant/man
nav:
  - About: about.md
  - Requirements: requirements.md
  - Download: download.md
  - Installation: installation.md
  - Run: run.md
  - Database: db.md
  - Errors: errors.md
  - Release Notes 1.x: release_notes_1.md
  - Contact: contact.md
  - Credits: credits.md
theme: readthedocs
